import type { CrawlRecipe } from '../crawl-recipe.js';

/** Public search API — discovered via network sniff (sportchek-ai / pipeline_clean.py). */
export const SPORTCHEK_CRAWL_RECIPE: CrawlRecipe = {
  version: 1,
  sources: ['platform', 'discovery'],
  discoveryMode: 'api',
  sitemapUrls: [],
  productUrlPattern: '/pdp/',
  listingUrlPattern: null,
  fetchStrategy: 'browser',
  extractionStrategy: 'json_ld',
  platform: 'salesforce',
  extractionHints: { imageJsonPaths: [], priceJsonPaths: [] },
  sampleProductUrls: [],
  agentFileUrl: null,
  notes: ['Sport Chek public search API at apim.sportchek.ca'],
  confidence: 1,
  api: {
    baseUrl: 'https://apim.sportchek.ca/v1/search/v2/search',
    method: 'GET',
    headers: {
      'Ocp-Apim-Subscription-Key': 'c01ef3612328420c9f5cd9277e815a0e',
      Accept: 'application/json, text/plain, */*',
      'Accept-Language': 'en-CA,en-US;q=0.7,en;q=0.3',
      bannerid: 'SC',
      baseSiteId: 'SC',
      'browse-mode': 'OFF',
      Origin: 'https://www.sportchek.ca',
      Referer: 'https://www.sportchek.ca/',
      'Sec-Fetch-Dest': 'empty',
      'Sec-Fetch-Mode': 'cors',
      'Sec-Fetch-Site': 'same-site',
      'service-client': 'sc/web',
      'service-version': 'v1',
      'User-Agent':
        'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:142.0) Gecko/20100101 Firefox/142.0',
      'x-web-host': 'www.sportchek.ca',
    },
    staticQuery: {
      store: '{SPORTCHEK_STORE}',
      location: '{SPORTCHEK_LOCATION}',
      sort: 'relevance',
      facets: 'true',
      includePricing: 'true',
    },
    categoryParam: {
      name: 'group',
      values: [
        { key: 'men', value: 'MEN', label: "Men's" },
        { key: 'women', value: 'WOMEN', label: "Women's" },
        { key: 'kids', value: 'KIDS', label: 'Kids' },
        { key: 'shop-by-sport', value: 'SHOP-BY-SPORT', label: 'Shop By Sport' },
        {
          key: 'activities-and-equipment',
          value: 'ACTIVITIES+EQUIPMENT',
          label: 'Activities & Equipment',
        },
        { key: 'outdoor', value: 'OUTDOOR', label: 'Outdoor' },
        { key: 'fan-shop', value: 'FAN-SHOP', label: 'Fan Shop' },
        { key: 'accessories', value: 'ACCESSORIES', label: 'Accessories' },
      ],
    },
    pagination: {
      pageParam: 'page',
      itemsPerPage: 10,
      totalPagesPath: 'pagination.total',
      maxPages: 100,
      delayMs: 500,
    },
    productsPath: 'products',
    fieldMap: {
      title: 'title',
      url: 'url',
      sku: ['skuId', 'code'],
      price: ['currentPrice.value', 'options[0].values[0].currentPrice.value'],
      listPrice: ['originalPrice.value', 'options[0].values[0].originalPrice.value'],
      image: 'images[0].url',
      brand: 'brand.label',
      description: 'featureBullets[0].description',
    },
    urlPrefix: 'https://www.sportchek.ca',
    currency: 'CAD',
  },
};
